# 0. Konfigurasi Server
server.port=8085

# 1. Koneksi Database (Support Docker Environment Variables)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_asset_management?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:W@hid123.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Konfigurasi JPA / Hibernate
# 'none' karena kita menggunakan Flyway untuk mengelola tabel
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Opsional: Menonaktifkan Open In View warning
spring.jpa.open-in-view=false